# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      #$ErrorActionPreference='continue'
      param($AppName)
      $appName=$AppName
      Write-Host $appName
      #Write-Host $env:Build_SourcesDirectory
      #$cdir=$env:Build_SourcesDirectory
      #Write-Host $cdir
      #$cdir=$(echo $(Build.SourcesDirectory))
      #Write-Host $cdir
      #jsonFilePath="$cdir\pipelineMetadata.json"
      #$jsondata = Get-Content -Raw -Path $jsonFilePath | ConvertFrom-Json
      #$appName = "QMSA"
      #Write-Host "##vso[task.setvariable variable=SonarProjectKey]$($jsondata.$appName.SonarQube.ProjectKey)"
    errorActionPreference: 'continue'